/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2022-10-11 07:13:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	//선언문  - 객체, 변수, 메소드 선언시 (연산은 x)
	int[] jumsu = {70,80,90};
	String[] names = {"김","이","박"};
	int a = 20;
	int b = 30;
	Date now = new Date();

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- 페이지 디렉티브 -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>웹 문서 테스트</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");

	//처리 구문-> 스크립트릿(scriptlet)
	int c;
	String name = "김기태";
	if(a>b) {
		c = a;
	} else {
		c = b;
	}
	for(int d=0;d<10;d++){
		out.println(name+d);
	}
	out.println("c 출력은 표현식");
	out.println(now);
	

      out.write("\r\n");
      out.write("<div id=\"result\"><!-- 각주 -->\r\n");
      out.print(c );
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.print(now );
      out.write("\r\n");
      out.write("<ul>\r\n");

	for(int e=0;e<3;e++) {

      out.write("\r\n");
      out.write("<li>");
      out.print(names [e] );
      out.write(' ');
      out.write(':');
      out.write(' ');
      out.print(jumsu[e] );
      out.write("</li>\r\n");

	}

      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("<a href=\"test01.jsp?id=kkt&pw=1234&name=김기태\">회원 데이터 - get</a>\r\n");
      out.write("\r\n");
      out.write("<form action=\"test02.jsp\" method=\"post\" name=\"login_form\">\r\n");
      out.write("\t<input name=\"id\" id=\"id\" placeholder=\"아이디 입력\"><br><br>\r\n");
      out.write("\t<input type=\"password\" name=\"pw\" id=\"pw\" placeholder=\"비밀번호 입력\"><br><br>\r\n");
      out.write("\t<input name=\"name\" id=\"name\" placeholder=\"이름 입력\"><br><br>\r\n");
      out.write("\t<input type=\"submit\" value=\"값 전송\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t<input type=\"reset\" value=\"취소\">\r\n");
      out.write("</form>\r\n");
      out.write("<div id=\"msg\">\r\n");

request.setCharacterEncoding("UTF-8");
String msg = request.getParameter("msg");
	if (msg!=null){

      out.write("\r\n");
      out.write("\t<strong>");
      out.print(msg  );
      out.write("</strong>\r\n");

	}

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
